# SPDX-License-Identifier: GPL-2.0-only
PACKAGE_NAME="dgx-spark-fan-control"
PACKAGE_VERSION="0.1.3"
BUILT_MODULE_NAME[0]="dgx_ec_fan_control"
BUILT_MODULE_LOCATION[0]="kernel"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hwmon"
MAKE[0]="make -C kernel KDIR=${kernel_source_dir}"
CLEAN="make -C kernel KDIR=${kernel_source_dir} clean"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_ARCH="^aarch64$"
